//created on: Dec 1, 2016
//author: Cesar Henrique Bernabe
package com.bioclassifier

import com.bioclassifier.Animal;

rule "Peixe 2"
	no-loop true
	salience 110
    when
        a : Animal( getRespiracao("bronquial") )
    then
    	a.setGrupo( "Peixes" );
        System.out.println("Peixe");
        update ( a )

end

rule "Peixe"
	no-loop true
	salience 100
    when
        a : Animal( grupo == null,
        			getHabitat("aquatico"),
        			getRevestimento("escamas") || getRevestimento("cartilagem"),
        			getLocomocao("nadar"),
        			getReproducao("ovoliparo"),
        			getAlimentacao("carnivoro") || getAlimentacao("herbivoro"),
        			getRespiracao("bronquial")
        			)
    then
    	a.setGrupo( "Peixes" );
        System.out.println("Peixe");
        update ( a )

end

rule "Salmao"
	no-loop true
	salience 90
    when
        a : Animal( grupo == "Peixes",
        			getRevestimento("cartilagem") && !getRevestimento("escamas"),
        			getAlimentacao("carnivoro") && !getAlimentacao("herbivoro")
        			)
    then
        System.out.println("Salmao");
end

rule "Tubarao"
	no-loop true
	salience 90
    when
        a : Animal( grupo == "Peixes",
        			getRevestimento("cartilagem") && !getRevestimento("escamas"),
        			getAlimentacao("carnivoro") && !getAlimentacao("herbivoro")
        			)
    then
        System.out.println("Tubarao");
end

rule "Anfibio"
	no-loop true
	salience 100
    when
        a : Animal( getHabitat("aquatico") || getHabitat("terrestre"),
        			getRevestimento("pele"),
        			getLocomocao("andar") || getLocomocao("rastejar") || getLocomocao("nadar"),
        			getReproducao("ovoliparo") || getReproducao("oviparo"),
        			getAlimentacao("carnivoro"),
        			getRespiracao("cutanea") || getRespiracao("pulmonar")
        			)
    then
    	a.setGrupo( "Anfibios" );
        System.out.println("Anfibio");
        update ( a )
end

rule "Sapo"
	no-loop true
	salience 90
    when
        a : Animal( grupo == "Anfibios",
        			!getReproducao("oviparo") && getReproducao("ovoliparo")
        			)
    then
        System.out.println("Sapo");
end

rule "Salamandra"
	no-loop true
	salience 90
    when
        a : Animal( grupo == "Anfibios",
        			getReproducao("oviparo") && !getReproducao("ovoliparo")
        			)
    then
        System.out.println("Salamandra");
end

rule "Repteis"
	no-loop true
	salience 100
    when
        a : Animal( getHabitat("aquatico") || getHabitat("terrestre"),
        			getRevestimento("escamas") || getRevestimento("cartilagem"),
        			getLocomocao("andar") || getLocomocao("rastejar") || getLocomocao("nadar"),
        			getReproducao("oviparo"),
        			getAlimentacao("carnivoro") || getAlimentacao("herbivoro"),
        			getRespiracao("pulmonar")
        			)
    then
    	a.setGrupo( "Repteis" );
        System.out.println("Repteis");
        update ( a )
end

rule "Jacare"
	no-loop true
	salience 90
    when
        a : Animal( grupo == "Repteis",
        			getRevestimento("escamas"),
        			getLocomocao("andar") && getLocomocao("nadar"),
        			getAlimentacao("carnivoro"),
        			getRespiracao("pulmonar")
        			)
    then
        System.out.println("Jacaré");
end

rule "Cobra"
	no-loop true
	salience 90
    when
        a : Animal( grupo == "Repteis",
        			getRevestimento("escamas"),
        			getLocomocao("rastejar") && getLocomocao("nadar"),
        			getAlimentacao("carnivoro"),
        			getRespiracao("pulmonar")
        			)
    then
        System.out.println("Cobra");
end

rule "Tartaruga"
	no-loop true
	salience 90
    when
        a : Animal( grupo == "Repteis",
        			getRevestimento("escamas") && getRevestimento("carapaca"),
        			getLocomocao("andar"),
        			getAlimentacao("herbivoro"),
        			getRespiracao("pulmonar")
        			)
    then
        System.out.println("Tartaruga");
end

rule "Aves"
	no-loop true
	salience 100
    when
        a : Animal( getRevestimento("penas") )
    then
    	a.setGrupo( "Aves" );
        System.out.println("Aves");
        update ( a )
end

rule "Pinguim"
	no-loop true
	salience 90
    when
        a : Animal( grupo == "Aves",
        			getHabitat("terrestre") && getHabitat("aquatico") && !getHabitat("aereo"),
        			getLocomocao("andar") && getLocomocao("nadar") && !getLocomocao("voar"),
        			getAlimentacao("carnivoro") && !getAlimentacao("herbivoro")
        			)
    then
        System.out.println("Pinguim");
end

rule "Pato"
	no-loop true
	salience 90
    when
        a : Animal( grupo == "Aves",
        			getHabitat("terrestre") && getHabitat("aquatico") && getHabitat("aereo"),
        			getLocomocao("andar") && getLocomocao("nadar") && getLocomocao("voar"),
        			getAlimentacao("herbivoro") && !getAlimentacao("carnivoro")
        			)
    then
        System.out.println("Pato");
end

rule "Galinha"
	no-loop true
	salience 90
    when
        a : Animal( grupo == "Aves",
        			getHabitat("terrestre") && !getHabitat("aquatico") && !getHabitat("aereo"),
        			getLocomocao("andar") && getLocomocao("voar") && !getLocomocao("nadar"),
        			getAlimentacao("herbivoro" ) && !getAlimentacao("carnivoro")
        			)
    then
        System.out.println("Galinha");
end

rule "Mamifero"
	no-loop true
	salience 100
    when
        a : Animal( getReproducao("viviparo") )
    then
    	a.setGrupo( "Mamifero" );
        System.out.println("Mamifero");
        update ( a )
end

rule "Macaco"
	no-loop true
	salience 90
    when
        a : Animal( grupo == "Mamifero",
        			getHabitat("terrestre") && !getHabitat("aquatico") && !getHabitat("aereo"),
        			getRevestimento("pele") && getRevestimento("pelo"),
        			getLocomocao("andar") && !getLocomocao("nadar") && !getLocomocao("voar")
        			)
    then
        System.out.println("Macaco");
end

rule "Baleia"
	no-loop true
	salience 90
    when
        a : Animal( grupo == "Mamifero",
        			getHabitat("aquatico") && !getHabitat("aereo") && !getHabitat("terrestre"),
        			getRevestimento("pele") && !getRevestimento("pelo"),
        			getLocomocao("nadar") && !getLocomocao("andar") && !getLocomocao("voar")
        			)
    then
        System.out.println("Baleia");
end

rule "Morcego"
	no-loop true
	salience 90
    when
        a : Animal( grupo == "Mamifero",
        			getHabitat("aereo") && !getHabitat("aquatico") && !getHabitat("terrestre"),
        			getRevestimento("pele") && !getRevestimento("pelo"),
        			getLocomocao("voar") && !getLocomocao("andar") && !getLocomocao("nadar")
        			)
    then
        System.out.println("Morcego");
end

rule "Desconhecido"
	no-loop true
	salience 0
	when 
		a : Animal( grupo == null )
	then 
		System.out.println("Ser desconhecido");
end

