//created on: Dec 3, 2016
package rules

import com.bioclassifier.Animal;
import com.bioclassifier.Result;


//------------- HABITAT -------------
rule "Terrestre"
	no-loop true
	salience 220

    when
        a : Animal( checkHabitat("terrestre") )
        r : Result()
    then
        r.countVote(Result.Grupo.ANFIBIO);
        r.countVote(Result.Grupo.REPTEIS);
        r.countVote(Result.Grupo.AVES);
        r.countVote(Result.Grupo.MAMIFERO);
        
end


//REGRA NAO FAZ DIFERENCA
/* rule "Aquatico"
	no-loop true
	salience 220

    when
        a : Animal( checkHabitat("aquatico") )
        r : Result()
    then
        r.countVote(Result.Grupo.PEIXE);
        r.countVote(Result.Grupo.ANFIBIO);
        r.countVote(Result.Grupo.REPTEIS);
        r.countVote(Result.Grupo.AVES);
        r.countVote(Result.Grupo.MAMIFERO);   
end */

rule "Aereo"
	no-loop true
	salience 220

    when
        a : Animal( checkHabitat("aereo") )
        r : Result()
    then
    	r.countVote(Result.Grupo.AVES);
        r.countVote(Result.Grupo.MAMIFERO);
        
end

//------------- RESPIRACAO -------------
rule "Bronquial"
no-loop true
	salience 250

    when
        a : Animal( checkRespiracao("bronquial") )
        r : Result()
    then
        r.countVote(Result.Grupo.PEIXE);
end

rule "Cutanea"
no-loop true
	salience 250

    when
        a : Animal( checkRespiracao("cutanea") )
        r : Result()
    then
        r.countVote(Result.Grupo.ANFIBIO);
end

rule "Pulmonar"
	no-loop true
	salience 220

    when
        a : Animal( checkRespiracao("pulmonar") )
        r : Result()
    then
    	r.countVote(Result.Grupo.ANFIBIO);
    	r.countVote(Result.Grupo.REPTEIS);
    	r.countVote(Result.Grupo.AVES);
        r.countVote(Result.Grupo.MAMIFERO);
end

//------------- LOCOMOCAO -------------
rule "Voar"
	no-loop true
	salience 220

    when
        a : Animal( checkLocomocao("voar") )
        r : Result()
    then
    	r.countVote(Result.Grupo.AVES);
        r.countVote(Result.Grupo.MAMIFERO);
end

rule "Andar"
	no-loop true
	salience 220

    when
        a : Animal( checkLocomocao("andar") )
        r : Result()
    then
    	r.countVote(Result.Grupo.ANFIBIO);
    	r.countVote(Result.Grupo.REPTEIS);
    	r.countVote(Result.Grupo.AVES);
        r.countVote(Result.Grupo.MAMIFERO);
end

//Regra nao faz diferenca
/* rule "Nadar"
	no-loop true
	salience 220

    when
        a : Animal( checkLocomocao("nadar") )
        r : Result()
    then
        r.countVote(Result.Grupo.PEIXE);
        r.countVote(Result.Grupo.ANFIBIO);
        r.countVote(Result.Grupo.REPTEIS);
        r.countVote(Result.Grupo.AVES);
        r.countVote(Result.Grupo.MAMIFERO); 
end */

rule "Rastejar"
	no-loop true
	salience 220

    when
        a : Animal( checkLocomocao("rastejar") )
        r : Result()
    then
        r.countVote(Result.Grupo.ANFIBIO);
        r.countVote(Result.Grupo.REPTEIS);
end

//------------- REVESTIMENTO -------------
rule "Penas"
	no-loop true
	salience 250

    when
        a : Animal( checkRevestimento("penas") )
        r : Result()
    then
        r.countVote(Result.Grupo.AVES);
end

rule "Pelo"
	no-loop true
	salience 250

    when
        a : Animal( checkRevestimento("pelo") )
        r : Result()
    then
        r.countVote(Result.Grupo.MAMIFERO);
end

rule "Escamas"
	no-loop true
	salience 220

    when
        a : Animal( checkRevestimento("escamas") )
        r : Result()
    then
        r.countVote(Result.Grupo.PEIXE);
        r.countVote(Result.Grupo.REPTEIS);
end

rule "Pele"
	no-loop true
	salience 220

    when
        a : Animal( checkRevestimento("pele") )
        r : Result()
    then
        r.countVote(Result.Grupo.ANFIBIO);
        r.countVote(Result.Grupo.MAMIFERO);
end

rule "Carapaca"
	no-loop true
	salience 250

    when
        a : Animal( checkRevestimento("carapaca") )
        r : Result()
    then
        r.countVote(Result.Grupo.REPTEIS);
end

rule "Cartilagem"
	no-loop true
	salience 220

    when
        a : Animal( checkRevestimento("cartilagem") )
        r : Result()
    then
        r.countVote(Result.Grupo.PEIXE);
        r.countVote(Result.Grupo.REPTEIS);
end

//------------- REPRODUCAO -------------
rule "Viviparo"
	no-loop true
	salience 250

    when
        a : Animal( checkReproducao("viviparo") )
        r : Result()
    then
        r.countVote(Result.Grupo.MAMIFERO);
end

rule "Oviparo"
	no-loop true
	salience 220

    when
        a : Animal( checkReproducao("oviparo") )
        r : Result()
    then
        r.countVote(Result.Grupo.ANFIBIO);
        r.countVote(Result.Grupo.REPTEIS);
        r.countVote(Result.Grupo.AVES);
end

rule "ovoliparo"
	no-loop true
	salience 220

    when
        a : Animal( checkReproducao("ovoliparo") )
        r : Result()
    then
        r.countVote(Result.Grupo.PEIXE);
        r.countVote(Result.Grupo.ANFIBIO);
end

//------------- ALIMENTACAO -------------

rule "Carnivoro"
	no-loop true
	salience 220
	
	when
		a : Animal( checkAlimentacao("carnivoro") )
		r : Result()
	then 
		r.countVote(Result.Grupo.PEIXE);
		r.countVote(Result.Grupo.ANFIBIO);
		r.countVote(Result.Grupo.REPTEIS);
		r.countVote(Result.Grupo.AVES);
		r.countVote(Result.Grupo.MAMIFERO);
end

rule "Herbivoro"
	no-loop true
	salience 220
	
	when
		a : Animal( checkAlimentacao("herbivoro") )
		r : Result()
	then 
		r.countVote(Result.Grupo.PEIXE);
		r.countVote(Result.Grupo.REPTEIS);
		r.countVote(Result.Grupo.AVES);
		r.countVote(Result.Grupo.MAMIFERO);
end


