//created on: Dec 4, 2016
package rules

import com.bioclassifier.Animal;
import com.bioclassifier.Result;

rule "Salmao"
	no-loop true
	salience 90
    when
    	r : Result( decisao == Result.Grupo.PEIXE )
        a : Animal( !checkRevestimento("cartilagem") && checkRevestimento("escamas"),
        			checkAlimentacao("carnivoro") && !checkAlimentacao("herbivoro")
        			)
    then
        System.out.println("O animal é: Salmao");
end

rule "Tubarao"
	no-loop true
	salience 90
    when
    	r : Result( decisao == Result.Grupo.PEIXE)
        a : Animal( checkRevestimento("cartilagem") && !checkRevestimento("escamas"),
        			checkAlimentacao("carnivoro") && !checkAlimentacao("herbivoro")
        			)
    then
        System.out.println("O animal é: Tubarao");
end

rule "Sapo"
	no-loop true
	salience 90
    when
    	r : Result( decisao == Result.Grupo.ANFIBIO)
        a : Animal( !checkReproducao("oviparo") && checkReproducao("ovoliparo")
        			)
    then
        System.out.println("O animal é: Sapo");
end

rule "Salamandra"
	no-loop true
	salience 90
    when
    	r : Result( decisao == Result.Grupo.ANFIBIO)
        a : Animal( checkReproducao("oviparo") && !checkReproducao("ovoliparo")
        			)
    then
        System.out.println("O animal é: Salamandra");
end

rule "Jacare"
	no-loop true
	salience 90
    when
    	r : Result( decisao == Result.Grupo.REPTEIS)
        a : Animal( checkRevestimento("escamas") && !checkRevestimento("carapaca"),
        			checkLocomocao("andar") && checkLocomocao("nadar") && !checkLocomocao("rastejar"),
        			checkAlimentacao("carnivoro") && !checkAlimentacao("herbivoro")
        			)
    then
        System.out.println("O animal é: Jacaré");
end

rule "Cobra"
	no-loop true
	salience 90
    when
    	r : Result( decisao == Result.Grupo.REPTEIS)
        a : Animal( checkRevestimento("escamas") && !checkRevestimento("carapaca"),
        			!checkLocomocao("andar") && checkLocomocao("nadar") && checkLocomocao("rastejar"),
        			checkAlimentacao("carnivoro") && !checkAlimentacao("herbivoro")
        			)
    then
        System.out.println("O animal é: Cobra");
end

rule "Tartaruga"
	no-loop true
	salience 90
    when
    	r : Result( decisao == Result.Grupo.REPTEIS)
        a : Animal( checkRevestimento("escamas") && checkRevestimento("carapaca"),
        			checkLocomocao("andar") && checkLocomocao("nadar") && !checkLocomocao("rastejar"),
        			!checkAlimentacao("carnivoro") && checkAlimentacao("herbivoro")
        			)
    then
        System.out.println("O animal é: Tartaruga");
end

rule "Pinguim"
	no-loop true
	salience 90
    when
    	r : Result( decisao == Result.Grupo.AVES)
        a : Animal( checkHabitat("terrestre") && checkHabitat("aquatico") && !checkHabitat("aereo"),
        			checkLocomocao("andar") && checkLocomocao("nadar") && !checkLocomocao("voar"),
        			checkAlimentacao("carnivoro") && !checkAlimentacao("herbivoro")
        			)
    then
        System.out.println("O animal é: Pnguim");
end

rule "Pato"
	no-loop true
	salience 90
    when
    	r : Result( decisao == Result.Grupo.AVES)
        a : Animal( checkHabitat("terrestre") && checkHabitat("aquatico") && checkHabitat("aereo"),
        			checkLocomocao("andar") && checkLocomocao("nadar") && checkLocomocao("voar"),
        			!checkAlimentacao("carnivoro") && checkAlimentacao("herbivoro")
        			)
    then
        System.out.println("O animal é: Pato");
end

rule "Galinha"
	no-loop true
	salience 90
    when
    	r : Result( decisao == Result.Grupo.AVES)
        a : Animal( checkHabitat("terrestre") && !checkHabitat("aquatico") && !checkHabitat("aereo"),
        			checkLocomocao("andar") && !checkLocomocao("nadar") && checkLocomocao("voar"),
        			!checkAlimentacao("carnivoro") && checkAlimentacao("herbivoro")
        			)
    then
        System.out.println("O animal é: Galinha");
end

rule "Macaco"
	no-loop true
	salience 90
    when
    	r : Result( decisao == Result.Grupo.MAMIFERO)
        a : Animal( checkHabitat("terrestre") && !checkHabitat("aquatico") && !checkHabitat("aereo"),
        			checkRevestimento("pele") && checkRevestimento("pelo"),
        			checkLocomocao("andar") && !checkLocomocao("nadar") && !checkLocomocao("voar")
        			)
    then
        System.out.println("O animal é: Macaco");
end

rule "Baleia"
	no-loop true
	salience 90
    when
    	r : Result( decisao == Result.Grupo.MAMIFERO)
        a : Animal( !checkHabitat("terrestre") && checkHabitat("aquatico") && !checkHabitat("aereo"),
        			checkRevestimento("pele") && !checkRevestimento("pelo"),
        			!checkLocomocao("andar") && checkLocomocao("nadar") && !checkLocomocao("voar")
        			)
    then
        System.out.println("O animal é: Baleia");
end

rule "Morcego"
	no-loop true
	salience 90
    when
    	r : Result( decisao == Result.Grupo.MAMIFERO)
        a : Animal( !checkHabitat("terrestre") && !checkHabitat("aquatico") && checkHabitat("aereo"),
        			checkRevestimento("pele") && !checkRevestimento("pelo"),
        			!checkLocomocao("andar") && !checkLocomocao("nadar") && checkLocomocao("voar")
        			)
    then
        System.out.println("O animal é: Morcego");
end


